name: Test resvg

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test
        shell: bash
        run: |
          cd /tmp
          git clone https://github.com/RazrFalcon/resvg
          cd resvg
          cargo package --list
          cd 
          cargo package --list --manifest-path /tmp/resvg/Cargo.toml
